db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "controle_gastos"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "control_adm"
      MYSQL_PASSWORD: "control_adm"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
