info:
  artifactId: '${project.name}'
  version: '${project.version}'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/controle_gastos?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
     ddl-auto: none