info:
  artifactId: '${project.name}'
  version: '${project.version}'

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/controle_gastos?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
#    username: root
#    password: 'root'
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#     ddl-auto: none



spring:
 datasource:
   initialize: true
   url: jdbc:h2:mem:controle_gastos;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
   driver-class-name: org.h2.Driver
   username: sa
   password: sa
 jpa:
   show-sql: true
   hibernate:
     ddl-auto: none